### ISSUE TITLE
Version without pressure sensor

### ISSUE THREAD

**Issue by cactusbob** [ovrheat/raspberry_rtl_wh1080#1]
Hi

Thanks for this code. Do you know how I can disable the pressure sensor bit of code? I don't have one yet and don't get any output

Thanks

Geraint

**Comment by ovrheat** [comment]
Hi Geraint, sorry for my late reply and thanks to you to have tested my code.
If you don't need pressure sensor code then you should better use directly [rtl_433 code from Merbanan](https://github.com/merbanan/rtl_433), which is the project I started from. It only reads data received from the RF section of the WH1080 sensors without the pressure code section, so compiling it is near the same way as for my project, but without the need of editing anything.
Ciao!

**Comment by Tom49** [comment]
Hello,
think I have the same problem, but with connected pressure sensor BMP180 ...
When I compile your code, I get no display  data from the WH1080. 
If I compile the original of rtl_433 code from Merbanan, the data will be received, of course without pressure data.
Looks like the receive of any data does not work, when I use the Code from your.
Do you have any idea...

Raspberry Pi 3
BMP 180
RTL2832U

Thanks

Thomas

**Comment by ovrheat** [comment]
Hi Tom,
unfortunately I have no RaspberryPi 3 to do some test ATM.  I assume that you have double-checked the correct BMP180 wiring to the Raspberry and all of the steps as described in the readme, so the first thing that I would try is to edit line 140 of /src/devices/fineoffset_wh1080.c  .
I would change /dev/i2c-1  to  /dev/i2c-0, or also to /dev/i2c-2 just to be sure, then recompile and try.
If it still doesn't work I suggest to try some of the Python test script for the BMP180 that you can easily find on the web, just to make sure that everything is ok with the sensor.
