### ISSUE TITLE
-U (utc)

### ISSUE THREAD

**Issue by johnsonfe** [ovrheat/raspberry_rtl_wh1080#2]
weewx with sdr needs the -U option (timestamp in utc) on rtl_433 but i get invalid option -U might be the
older version of rtl_433 
"TZ=utc rtl_433 -F json" works but can't incorporate it into weewx is there a way this can be added...

thanks Frank
johnsonfe@hotmail.com

**Comment by ovrheat** [comment]
Yes Frank, this is based on an (now) old version of rtl_433. I'll take a look as soon as possible to update the project.

**Comment by johnsonfe** [comment]
thank you so much...
frank

**Comment by ovrheat** [comment]
...Updated!  Please read notes in the README because of some little (unavoidable) changes.
Enjoy!

**Comment by johnsonfe** [comment]
thanks again works...
Frank
