### ISSUE TITLE
making it work with weewx

### ISSUE THREAD

**Issue by willie42** [ovrheat/raspberry_rtl_wh1080#3]
I wanted to use your code with weewx.
There is a fantastic sdr-diver for weewx: https://github.com/matthewwall/weewx-sdr

But this one of course does not transmit the pressure values.

So I had to make some changes in your /src/devices/fineoffset_1080.c
At the end „PRESENTING DATA“ I changed the identifier - and pressure to pressure_hPa

```
678c685
< 			"model", 	"", 		DATA_STRING,	"Fine Offset WH1080 Weather Station",
---
> 			"model", 	"", 		DATA_STRING,	"Fine Offset WH1080 weather station",
683c690
< 			"pressure",	"Pressure",	DATA_FORMAT, "%.02f hPa",	DATA_DOUBLE, pressure,
---
> 			"pressure_hPa",	"Pressure",	DATA_FORMAT, "%.02f hPa",	DATA_DOUBLE, pressure,
```

With this changes the data was recognized and parsed by the driver (you can call it directly and view the output).

Next I had to change things in the driver itself. The driver comes as a ZIP-archive. Unpacked (weewx-sdr-master/bin/user/sdr.py) I´ll have to add lines for the pressure:

```
815c815,817
< # 'Wind string': ['wind_dir_ord', None, None],
---
> 'Pressure':
> ['pressure', re.compile('([\d.-]+) hPa'), lambda x: float(x)],
> # 'Wind string': ['wind_dir_ord', None, None],
819a822
> # inTemp
838a842
> pkt['pressure'] = Packet.get_float(obj, 'pressure_hPa')
900a905
> pkt['pressure'] = Packet.get_float(obj, 'pressure_hPa')
2183c2188
```

That worked for me. Maybe it helps someone else - or maybe someone with more understanding of the code integrates it.

**Comment by willie42** [comment]
Annother change: The code gave me 10 times as much rain as there really was. I had to change 

return (float)rain_raw * 0.3f;
to
return (float)rain_raw * 0.03f;

now it seams to work correct.

**Comment by ovrheat** [comment]
Nice, thank you for sharing this!
Let me know if there is something I can do
