### ISSUE TITLE
build fails with latest buster lite image ...

### ISSUE THREAD

**Issue by linksfuchs** [ovrheat/raspberry_rtl_wh1080#4]
Hi,
first - just a bit of a background:
I have a running setup with the BM085 since like forever and it works really well.
It just happened that a recent storm sent my trusted station flying and I had to purchase a new one ... to my surprise it was equipped with an UV sensor.
So I found out, that your latest version already supports that particular sensor.
I did build the newest version on the original raspberry and it worked right out of the box.
That pi is still on "jessie" so I think the libraries are as they were 2018.

Now to the problem:
I wanted to rewrite some of my own code (a little python script datalogger with the usual upload functions) to include the uv data and didn't want try it out on my "operational" pi.
So I set up a new pi (3B+) with the newest buster image and tried to build the necessary packages -> rtl-sdr and your code.

Turns out, something changed along the way from 2018 and your code is not building anymore.
Here is the error message:
```sh
[ 20%] Linking C executable rtl_433
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `bmp085_i2c_Read_Int':
fineoffset_wh1080.c:(.text+0x5c): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `bmp085_i2c_Write_Byte':
fineoffset_wh1080.c:(.text+0x8c): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `bmp085_i2c_Read_Block':
fineoffset_wh1080.c:(.text+0xa8): undefined reference to `i2c_smbus_read_i2c_block_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `bmp085_Calibration':
fineoffset_wh1080.c:(.text+0xf0): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x11c): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x148): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x174): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x1a0): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o:fineoffset_wh1080.c:(.text+0x1cc): more undefined references to `i2c_smbus_read_word_data' follow
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `bmp085_ReadUT':
fineoffset_wh1080.c:(.text+0x35c): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x378): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `bmp085_ReadUP':
fineoffset_wh1080.c:(.text+0x40c): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x430): undefined reference to `i2c_smbus_read_i2c_block_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `read_int_temp':
fineoffset_wh1080.c:(.text+0x640): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x65c): undefined reference to `i2c_smbus_read_word_data'
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/fineoffset_wh1080.c.o: in function `read_press':
fineoffset_wh1080.c:(.text+0x784): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: fineoffset_wh1080.c:(.text+0x7a0): undefined reference to `i2c_smbus_read_word_data'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/rtl_433.dir/build.make:220: src/rtl_433] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/rtl_433.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
I "googled" a bit around and it seems either something about the included `linux/i2c-dev.h`or some shenanigans of the newest gcc ... idk ...

That all is quite out of  my league so I wanted to ask, if there is a chance, you could look into it?

It would be very much appreciated ... :-)

Cheers
  Thomas

**Comment by pv42** [comment]
This issue seems to be related to `libi2c-dev` requiring to link libi2c since verion 4.x.
It should be fixed by adding the line 
`target_link_libraries(rtl_433 i2c)` in **src**/CMakeLists.txt below `target_link_libraries(rtl_433 m)`.

**Comment by linksfuchs** [comment]
Haha ... Thank you ... 
"... better late than never ..." (ALF 1986 - just before blowing up the kitchen)
Yeah - I had to go with another solution:
Now I use the "Adafruit_BMP.BMP085" python library and read the values directly whenever there is a new dataset to write.
